language: rust

if: branch = master

install:
  # This only needs to run, to generate the cache. After that, it is done.
  # - cargo install cargo-screeps
  - cat screeps-secure.toml | sed "s/TOKEN/$AUTH/" > screeps.toml

script:
  - cargo screeps upload

##########################################
# Cache Cargo subcommand
##########################################
# https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
    - target/wasm32*

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry
##########################################
