language: rust

if: branch = master

install:
  # - cargo install cargo-screeps
  # - cat screeps.toml | sed "r/TOKEN/$AUTH/" > screeps.toml
  - cat screeps-secure.toml | sed "s/TOKEN/$TEST/" > screeps.toml

script:
  - cat screeps.toml
  # - cargo screeps upload
