[package]
name = "screeps_game"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.5"
screeps-game-api = "0.7"
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
